# Generated by Django 2.2.24 on 2023-04-08 11:36

from django.db import migrations
import phonenumbers


def set_pure_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(pure_phone_number):
            flat.owner_pure_phone = pure_phone_number
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_pure_phone_number)
    ]
