# Generated by Django 2.2.24 on 2023-04-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230409_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim',
            new_name='text',
        ),
    ]
